name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'test:')
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          url: ${{ secrets.TEST_URL }}
          token: ${{ secrets.TEST_TOKEN }}
          file: __tests__/upload-test.pdf
